### ISSUE TITLE
(New Endpoint) Single Benchmark Info

### ISSUE THREAD

**Issue by wmunyan** [CISecurity/OptimusAPI#34]
Current endpoints include a `GET /benchmarks` to list ALL benchmarks, and the `/benchmarks/{workbenchId}/{format}` endpoint to download a particular serialization.

I have a couple of recommendations for enhancements:

First, in the:
```
GET /benchmarks
```
...endpoint, could you add hashes to each benchmark entry?  Perhaps an array consisting of SHA1, SHA256, and MD5 hashes for each benchmark?

Second, a new endpoint:
```
GET /benchmarks/{workbenchId}
```
...that shows the information (including the above-mentioned hashes) for an individual benchmark.

If a member is bulk downloading benchmark content via the API, hash values for each benchmark will help determine whether or not a particular `{workbenchId}` has been modified, or if they can skip downloading that file/files

**Comment by jabuddie** [comment]
Thank you for sharing these ideas with us. We agree that there's opportunity to improve metadata available as well as functionality around the responses that output available metadata. These have been noted as feature enhancement requests for future consideration. 
Thanks again,
Justine

**Comment by wmunyan** [comment]
Any updates on adding this endpoint?

**Comment by bbermann-cis** [comment]
An endpoint has been added to display information for a specific benchmark
https://ssapi.docs.cisecurity.org/en/stable/endpoints/benchmark.html
