### ISSUE TITLE
Documentation for List Available Benchmarks does not match the actual endpoint

### ISSUE THREAD

**Issue by treguly** [CISecurity/OptimusAPI#46]
Within the List Available Benchmarks documentation, in the Description/Fields section, the one of the response elements is listed as 'benchmarkUrl'. When you get data back from the endpoint, the actual element value is benchmarksUrl.

**Comment by bbermann-cis** [comment]
Thanks for letting us know about this issue. We've updated the documentation. 
https://ssapi.docs.cisecurity.org/en/stable/endpoints/benchmark.html
https://ssapi.docs.cisecurity.org/en/stable/endpoints/list-benchmarks.html
